name: 'retail'
version: '1.0'
config-version: 2

profile: 'retail'

models:
  retail:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
